#===================================#
# Appearance Configuration Settings
#===================================#
appearance:
  locale: en_US
  unitSystem: metric
  timeFormat: 24
  sportTypesSortingOrder: []

#---------------------------------#
# Date Format Configuration Settings
#---------------------------------#
  dateFormat:
    short: d-m-y
    normal: d-m-Y

#---------------------------------#
# Dashboard Configuration Settings
#---------------------------------#
  dashboard:
    layout:
      - widget: mostRecentActivities
        width: 66
        enabled: true
        config:
          numberOfActivitiesToDisplay: 5
      - widget: introText
        width: 33
        enabled: true
      - widget: trainingGoals
        width: 33
        enabled: false
        config:
          goals: []
      - widget: weeklyStats
        width: 100
        enabled: true
        config:
          metricsDisplayOrder:
            - distance
            - movingTime
            - elevation
      - widget: peakPowerOutputs
        width: 50
        enabled: true
      - widget: heartRateZones
        width: 50
        enabled: true
      - widget: activityGrid
        width: 100
        enabled: true
      - widget: monthlyStats
        width: 100
        enabled: true
        config:
          enableLastXYearsByDefault: 10
          metricsDisplayOrder:
            - distance
            - movingTime
            - elevation
      - widget: trainingLoad
        width: 100
        enabled: true
      - widget: weekdayStats
        width: 50
        enabled: true
      - widget: dayTimeStats
        width: 50
        enabled: true
      - widget: distanceBreakdown
        width: 100
        enabled: true
      - widget: yearlyStats
        width: 100
        enabled: true
        config:
          enableLastXYearsByDefault: 10
          metricsDisplayOrder:
            - distance
            - movingTime
            - elevation
      - widget: zwiftStats
        width: 50
        enabled: true
      - widget: gearStats
        width: 50
        enabled: true
        config:
          includeRetiredGear: true
      - widget: eddington
        width: 50
        enabled: true
      - widget: challengeConsistency
        width: 50
        enabled: true
        config:
          challenges: []
      - widget: mostRecentChallengesCompleted
        width: 50
        enabled: true
        config:
          numberOfChallengesToDisplay: 5
      - widget: ftpHistory
        width: 50
        enabled: true
      - widget: athleteWeightHistory
        width: 50
        enabled: true

#---------------------------------#
# Heatmap Configuration Settings
#---------------------------------#
  heatmap:
    polylineColor: "#fc6719"
    tileLayerUrl: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    enableGreyScale: true

#---------------------------------#
# Photos Configuration Settings
#---------------------------------#
  photos:
    hidePhotosForSportTypes: []
    defaultEnabledFilters:
      sportTypes: []
      countryCode: null