#===================================#
# Daemon Configuration Settings
#===================================#
daemon:

#---------------------------------#
# Cron Job Configuration Settings
#---------------------------------#
  cron:
    - action: importDataAndBuildApp
      expression: 0 14 * * *
      enabled: true
    - action: gearMaintenanceNotification
      expression: 0 14 * * *
      enabled: false
    - action: appUpdateAvailableNotification
      expression: 0 14 * * *
      enabled: false