#===================================#
# Integrations Configuration Settings
#===================================#
integrations:

#---------------------------------#
# Notifications Configuration Settings
#---------------------------------#
  notifications:
    services: []

#---------------------------------#
# AI Integration Configuration Settings
#---------------------------------#
  ai:
    enabled: false
    enableUI: false
    provider: PROVIDER-YOU-CHOOSE
    configuration:
      key: YOUR-API-KEY
      model: MODEL-NAME
      url: http://host.docker.internal:11434/api