#===================================#
# Metrics Configuration Settings
#===================================#
metrics:

#---------------------------------#
# Eddington Score Configuration Settings
#---------------------------------#
  eddington:
    - label: Ride
      showInNavBar: true
      showInDashboardWidget: true
      sportTypesToInclude:
        - Ride
        - MountainBikeRide
        - GravelRide
        - VirtualRide
    - label: Run
      showInNavBar: true
      showInDashboardWidget: true
      sportTypesToInclude:
        - Run
        - TrailRun
        - VirtualRun
    - label: Walk
      showInNavBar: false
      showInDashboardWidget: false
      sportTypesToInclude:
        - Walk
        - Hike