#===================================#
# Gear Configuration Settings
#===================================#
gear:

#---------------------------------#
# Strava Gear Configuration Settings
#---------------------------------#
  stravaGear:
    - gearId: g12337767
      purchasePrice:
        amountInCents: 123456
        currency: EUR

#---------------------------------#
# Custom Gear Configuration Settings
#---------------------------------#
  customGear:
    enabled: true
    hashtagPrefix: sfs
    customGears:
      - tag: peddle-board
        label: Peddle Board
        isRetired: false
        purchasePrice: null
        amountInCents: 123456
        currency: EUR
      - tag: workout-shoes
        label: Fancy workout shoes
        isRetired: true