#---------------------------------------------------#
# Table of Contents
#---------------------------------------------------#
# - General configuration settings
#   - Athlete configuration settings
# - Appearance configuration settings
# - Import configuration settings
# - Metrics configuration settings
#   - Eddington score configuration settings
# - Gear configuration settings
#   - Strava gear configuration settings
#   - Custom gear configuration settings
# - Zwift configuration settings
# - Integrations configuration settings
#   - Notifications configuration settings
#   - AI integrations configuration settings
# - Daemon configuration settings
#   - Cron job configuration settings
#

#===================================#
# General Configuration Settings
#===================================#
general:
  appUrl: http://localhost:8080/
  appSubTitle: null
  profilePictureUrl: null

#---------------------------------#
# Athlete Configuration Settings
#---------------------------------#
  athlete:
    heartRateZones:
      mode: relative
    ftpHistory:
      running: []

#===================================#
# Appearance Configuration Settings
#===================================#
appearance:
  locale: en_US

#===================================#
# Import Configuration Settings
#===================================#
import:
  numberOfNewActivitiesToProcessPerImport: 250
  sportTypesToImport: []
  activityVisibilitiesToImport: []
  skipActivitiesRecordedBefore: null
  activitiesToSkipDuringImport: []
  optInToSegmentDetailImport: false
  webhooks:
    enabled: true
    verifyToken: ""
    checkIntervalInMinutes: 1

#===================================#
# Metrics Configuration Settings
#===================================#
metrics:

#---------------------------------#
# Eddington Score Configuration Settings
#---------------------------------#
  eddington:
    - label: Ride
      showInNavBar: true
      showInDashboardWidget: true
      sportTypesToInclude:
        - Ride
        - MountainBikeRide
        - GravelRide
        - VirtualRide
    - label: Run
      showInNavBar: true
      showInDashboardWidget: true
      sportTypesToInclude:
        - Run
        - TrailRun
        - VirtualRun
    - label: Walk
      showInNavBar: false
      showInDashboardWidget: false
      sportTypesToInclude:
        - Walk
        - Hike

#===================================#
# Gear Configuration Settings
#===================================#
gear:

#---------------------------------#
# Strava Gear Configuration Settings
#---------------------------------#
  stravaGear: []

#---------------------------------#
# Custom Gear Configuration Settings
#---------------------------------#
  customGear: []

#===================================#
# Zwift Configuration Settings
#===================================#
zwift:
  level: null
  racingScore: null

#===================================#
# Integrations Configuration Settings
#===================================#
integrations:

#---------------------------------#
# Notifications Configuration Settings
#---------------------------------#
  notifications:
    services: []

#---------------------------------#
# AI Integration Configuration Settings
#---------------------------------#
  ai:
    enabled: false
    enableUI: false
    configuration:
      url: null

#===================================#
# Daemon Configuration Settings
#===================================#
daemon:

#---------------------------------#
# Cron Job Configuration Settings
#---------------------------------#
  cron:
    - action: importDataAndBuildApp
      expression: 0 14 * * *
      enabled: true
    - action: gearMaintenanceNotification
      expression: 0 14 * * *
      enabled: false
    - action: appUpdateAvailableNotification
      expression: 0 14 * * *
      enabled: false