name: Build and Publish Docker Image

on:
  push:
    # branches:
      # - main
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Config Tool ---
      - name: Extract metadata (config-tool)
        id: meta-config-tool
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stats-for-strava-config-tool
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ !contains(github.ref, '-') }}

      - name: Build and push config-tool image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta-config-tool.outputs.tags }}
          labels: ${{ steps.meta-config-tool.outputs.labels }}

      # --- Strava Runner ---
      - name: Extract metadata (runner)
        id: meta-runner
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/strava-runner
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ !contains(github.ref, '-') }}

      - name: Build and push runner image
        uses: docker/build-push-action@v5
        with:
          context: ./runner
          push: true
          tags: ${{ steps.meta-runner.outputs.tags }}
          labels: ${{ steps.meta-runner.outputs.labels }}

      # --- Strava Command Helper ---
      - name: Extract metadata (helper)
        id: meta-helper
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/strava-command-helper
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ !contains(github.ref, '-') }}

      - name: Build and push helper image
        uses: docker/build-push-action@v5
        with:
          context: ./helper
          push: true
          tags: ${{ steps.meta-helper.outputs.tags }}
          labels: ${{ steps.meta-helper.outputs.labels }}
